### ISSUE TITLE
cannot import name 'wcprobe' from 'ntwork.wc'

### ISSUE THREAD

**Issue by bay1ts** [Kaguya233qwq/WeWorkBot#3]
D:\Develop\ntwork-master\venv\Scripts\python.exe D:\Develop\ntwork-master\examples\send_text.py 
Traceback (most recent call last):
  File "D:\Develop\ntwork-master\examples\send_text.py", line 4, in <module>
    import ntwork
  File "D:\Develop\ntwork-master\ntwork\__init__.py", line 2, in <module>
    from .core.wework import WeWork
  File "D:\Develop\ntwork-master\ntwork\core\wework.py", line 3, in <module>
    from ntwork.core.mgr import WeWorkMgr
  File "D:\Develop\ntwork-master\ntwork\core\mgr.py", line 3, in <module>
    from ntwork.wc import wcprobe
ImportError: cannot import name 'wcprobe' from 'ntwork.wc' (D:\Develop\ntwork-master\ntwork\wc\__init__.py)

**Comment by wtk-boss** [comment]
处理了了吗

**Comment by Kaguya233qwq** [comment]
请使用我的项目主页的ntwork中的的备份release，并在本地导入
